<?php
/**
 * Title: Complete Marine Doors page
 * Slug: aluteco/marine-doors-page
 * Categories: aluteco-pages
 * Description: Editable Marine Doors product page.
 */

$hero_url    = esc_url( get_theme_file_uri( '/assets/generated/hero-marine-doors.png' ) );
$sliding_url = esc_url( get_theme_file_uri( '/assets/photos/marine-doors-sliding.png' ) );
$folding_url = esc_url( get_theme_file_uri( '/assets/photos/marine-doors-folding.png' ) );
$windows_url = esc_url( get_theme_file_uri( '/assets/photos/marine-doors-pop-up-slide.png' ) );
$custom_url  = esc_url( get_theme_file_uri( '/assets/photos/marine-doors-custom.png' ) );
?>
<!-- wp:cover {"url":"<?php echo $hero_url; ?>","dimRatio":0,"minHeight":80,"minHeightUnit":"vh","align":"full","className":"hero hero-product hero-marine"} -->
<div class="wp-block-cover alignfull hero hero-product hero-marine" style="min-height:80vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Marine door engineering concept on a yacht" src="<?php echo $hero_url; ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"hero-copy reveal","layout":{"type":"default"}} --><div class="wp-block-group hero-copy reveal"><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Marine<br>Doors</h1><!-- /wp:heading --><!-- wp:separator {"className":"blue-line"} --><hr class="wp-block-separator has-alpha-channel-opacity blue-line"/><!-- /wp:separator --><!-- wp:paragraph --><p>High performance door systems<br>for marine environments</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"className":"product-tabs shell","layout":{"type":"grid","columnCount":4}} -->
<div class="wp-block-group product-tabs shell"><!-- wp:paragraph --><p><a href="#sliding">Sliding Doors</a></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#folding">Folding Doors</a></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#windows">Pop-up &amp; Slide Windows</a></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#custom">Custom Doors</a></p><!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"anchor":"sliding","className":"marine-row","layout":{"type":"default"}} -->
<div id="sliding" class="wp-block-group marine-row"><!-- wp:group {"className":"product-info reveal","layout":{"type":"default"}} --><div class="wp-block-group product-info reveal"><!-- wp:paragraph {"className":"number"} --><p class="number">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">Sliding Doors</h2><!-- /wp:heading --><!-- wp:separator {"className":"blue-line small"} --><hr class="wp-block-separator has-alpha-channel-opacity blue-line small"/><!-- /wp:separator --><!-- wp:paragraph --><p>Engineered for all kinds of yachts.</p><!-- /wp:paragraph --><!-- wp:group {"className":"feature-icons","layout":{"type":"grid","columnCount":2}} --><div class="wp-block-group feature-icons"><!-- wp:paragraph --><p>Unique style and functional solution</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Structurally glazing</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Extremely optimized construction</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Many door configurations</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"yacht-photo-one"} --><figure class="wp-block-image size-full yacht-photo-one"><img src="<?php echo $sliding_url; ?>" alt="Sliding marine doors opening to a yacht deck"/></figure><!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"anchor":"folding","className":"marine-row reverse","layout":{"type":"default"}} -->
<div id="folding" class="wp-block-group marine-row reverse"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"yacht-photo-two"} --><figure class="wp-block-image size-full yacht-photo-two"><img src="<?php echo $folding_url; ?>" alt="Fully opened folding doors on a yacht"/></figure><!-- /wp:image --><!-- wp:group {"className":"product-info reveal","layout":{"type":"default"}} --><div class="wp-block-group product-info reveal"><!-- wp:paragraph {"className":"number"} --><p class="number">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">Folding Doors</h2><!-- /wp:heading --><!-- wp:separator {"className":"blue-line small"} --><hr class="wp-block-separator has-alpha-channel-opacity blue-line small"/><!-- /wp:separator --><!-- wp:paragraph --><p>Create fully open transitions between interior and exterior spaces.</p><!-- /wp:paragraph --><!-- wp:group {"className":"feature-icons","layout":{"type":"grid","columnCount":2}} --><div class="wp-block-group feature-icons"><!-- wp:paragraph --><p>Very solid construction</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Adjustable hinges</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Multiple configuration option</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Wide opening space</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"anchor":"windows","className":"marine-row","layout":{"type":"default"}} -->
<div id="windows" class="wp-block-group marine-row"><!-- wp:group {"className":"product-info reveal","layout":{"type":"default"}} --><div class="wp-block-group product-info reveal"><!-- wp:paragraph {"className":"number"} --><p class="number">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">Pop-up &amp; Slide Windows</h2><!-- /wp:heading --><!-- wp:separator {"className":"blue-line small"} --><hr class="wp-block-separator has-alpha-channel-opacity blue-line small"/><!-- /wp:separator --><!-- wp:paragraph --><p>Discreet integration. Clean lines. Perfect solution for navigator windows.</p><!-- /wp:paragraph --><!-- wp:group {"className":"feature-icons","layout":{"type":"grid","columnCount":2}} --><div class="wp-block-group feature-icons"><!-- wp:paragraph --><p>Pop-up and slide</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Non visible profiles</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Smooth operating</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Glass thickness 6-10 mm</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"yacht-photo-three"} --><figure class="wp-block-image size-full yacht-photo-three"><img src="<?php echo $windows_url; ?>" alt="Pop-up and slide windows on a motor yacht"/></figure><!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"anchor":"custom","className":"marine-row reverse","layout":{"type":"default"}} -->
<div id="custom" class="wp-block-group marine-row reverse"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"yacht-photo-four"} --><figure class="wp-block-image size-full yacht-photo-four"><img src="<?php echo $custom_url; ?>" alt="Tailor-made curved marine doors at sunset"/></figure><!-- /wp:image --><!-- wp:group {"className":"product-info reveal","layout":{"type":"default"}} --><div class="wp-block-group product-info reveal"><!-- wp:paragraph {"className":"number"} --><p class="number">04</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">Custom Doors</h2><!-- /wp:heading --><!-- wp:separator {"className":"blue-line small"} --><hr class="wp-block-separator has-alpha-channel-opacity blue-line small"/><!-- /wp:separator --><!-- wp:paragraph --><p>Tailored engineering solutions for unique marine applications.</p><!-- /wp:paragraph --><!-- wp:group {"className":"feature-icons","layout":{"type":"grid","columnCount":2}} --><div class="wp-block-group feature-icons"><!-- wp:paragraph --><p>High quality and durability</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Designed according to norm ISO 12216</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Built for marine environment</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Many door configurations</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
<!-- /wp:group -->
